### ISSUE TITLE
Foreground Service Error in android 8.0

### ISSUE THREAD

**Issue by Hanzala717** [metinkale38/prayer-times-android#115]
03-29 15:57:51.239 22145-22145/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qibla.direction.finder, PID: 22145
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1870)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by metinkale38** [comment]
seems like you changed the targetApi to Oreo. please revert it back to 25, because it needs some changes...

**Comment by Hanzala717** [comment]
are you working on it ??

I have to test it on Oreo please update it .

**Comment by metinkale38** [comment]
i didnt test with Oreo yet, but normally it should work with target api 25.

you should not need startForegroundService with lower targetApi.
